/**
 * @file metamodel.c
 *
 * Define UML concepts of the metamodel.
 *
 * This file is automatically generated by the uml-serializer-c tool.
 * Do not modify manually.
 *
 * @author Matthias Brun (matthias.brun@eseo.fr)
 * @author Valentin Besnard (valentin.besnard@eseo.fr)
 */
 
#include <stddef.h>
#include "metamodel.h"

/**
 * Macro to used if there is a hole.
 * A white space is present in the descriptor table if the considered class has not this attribute.
 */
#define NO_DESC_TYPE   (0)
/**
 * The table of descriptor offsets for the class Property.
 */
uint8_t offsets_UML_Property[NB_DESC_INDEX] = {
	offsetof(UML_Property, visibility),
	offsetof(UML_Property, name),
	offsetof(UML_Property, type),
	offsetof(UML_Property, lower),
	offsetof(UML_Property, association),
	offsetof(UML_Property, aggregation),
	offsetof(UML_Property, class),
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE
};
/**
 * Macro to used if there is a hole.
 * A white space is present in the descriptor table if the considered class has not this attribute.
 */
#define NO_DESC_TYPE   (0)
/**
 * The table of descriptor offsets for the class Class.
 */
uint8_t offsets_UML_Class[NB_DESC_INDEX] = {
	offsetof(UML_Class, visibility),
	offsetof(UML_Class, name),
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	offsetof(UML_Class, ownedConnector),
	offsetof(UML_Class, ownedAttribute),
	offsetof(UML_Class, classifierBehavior),
	offsetof(UML_Class, interfaceRealization),
	offsetof(UML_Class, ownedPort),
	offsetof(UML_Class, c_kind),
	offsetof(UML_Class, superClass),
	offsetof(UML_Class, isActive),
	offsetof(UML_Class, ownedReception),
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE
};
/**
 * Macro to used if there is a hole.
 * A white space is present in the descriptor table if the considered class has not this attribute.
 */
#define NO_DESC_TYPE   (0)
/**
 * The table of descriptor offsets for the class Port.
 */
uint8_t offsets_UML_Port[NB_DESC_INDEX] = {
	offsetof(UML_Port, visibility),
	offsetof(UML_Port, name),
	offsetof(UML_Port, type),
	offsetof(UML_Port, lower),
	offsetof(UML_Port, association),
	offsetof(UML_Port, aggregation),
	offsetof(UML_Port, class),
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	NO_DESC_TYPE,
	offsetof(UML_Port, end),
	offsetof(UML_Port, c_index),
	offsetof(UML_Port, isConjugated),
	offsetof(UML_Port, provided),
	offsetof(UML_Port, isBehavior),
	offsetof(UML_Port, required)
};
/**
 * The global offsets table for all classes that have multiple inheritance.
 */
uint8_t * offsets_table[NB_MI_CLASSES] = {
	offsets_UML_Property,
	offsets_UML_Class,
	offsets_UML_Port
};
