

@startuml
	package Environment <<card>> {
		object "comPlayer : CommunicationPlayer" as ChallengeEnv_Environment_comPlayer {
			tcpPort = 9003
		}
		object "comReferee : CommunicationReferee" as ChallengeEnv_Environment_comReferee {
			tcpPort = 9007
		}
		ChallengeEnv_Environment_comPlayer -- "controllerToPlayerPortEnv" Environment : CommunicationPlayer_ControllerToPlayerPortEnv
		ChallengeEnv_Environment_comReferee -- "controllerToRefereePortEnv" Environment : CommunicationReferee_ControllerToRefereePortEnv
		ChallengeEnv_Environment_comPlayer -- "trajToPlayerPortEnv" Environment : CommunicationPlayer_TrajToPlayerPortEnv
		ChallengeEnv_Environment_comReferee -- "trajToRefereePortEnv" Environment : CommunicationReferee_TrajToRefereePortEnv
	}
@enduml
