

@startuml


	class "[[ChallengeSystem%3A%3AControllerToPlayerPortSys-Class.svg ChallengeSystem::ControllerToPlayerPortSys]]" as ChallengeSystem_ControllerToPlayerPortSys
	class "[[ChallengeEnv%3A%3AControllerToPlayerPortEnv-Class.svg ChallengeEnv::ControllerToPlayerPortEnv]]" as ChallengeEnv_ControllerToPlayerPortEnv
	class "[[ChallengeSystem%3A%3AControllerToRefereePortSys-Class.svg ChallengeSystem::ControllerToRefereePortSys]]" as ChallengeSystem_ControllerToRefereePortSys
	class "[[ChallengeEnv%3A%3AControllerToRefereePortEnv-Class.svg ChallengeEnv::ControllerToRefereePortEnv]]" as ChallengeEnv_ControllerToRefereePortEnv
	class "[[ChallengeSystem%3A%3ATrajToPlayerPortSys-Class.svg ChallengeSystem::TrajToPlayerPortSys]]" as ChallengeSystem_TrajToPlayerPortSys
	class "[[ChallengeEnv%3A%3ATrajToPlayerPortEnv-Class.svg ChallengeEnv::TrajToPlayerPortEnv]]" as ChallengeEnv_TrajToPlayerPortEnv
	class "[[ChallengeSystem%3A%3ATrajToRefereePortSys-Class.svg ChallengeSystem::TrajToRefereePortSys]]" as ChallengeSystem_TrajToRefereePortSys
	class "[[ChallengeEnv%3A%3ATrajToRefereePortEnv-Class.svg ChallengeEnv::TrajToRefereePortEnv]]" as ChallengeEnv_TrajToRefereePortEnv
	class "Main" as ChallengeMain_Main {
		+♦ system : [[ChallengeSystem%3A%3ASystem-Class.svg System]]
		+♦ environment : [[ChallengeEnv%3A%3AEnvironment-Class.svg Environment]]
	}
	ChallengeSystem_ControllerToPlayerPortSys -- ChallengeEnv_ControllerToPlayerPortEnv : controllerToPlayerPortEnv
	ChallengeSystem_ControllerToRefereePortSys -- ChallengeEnv_ControllerToRefereePortEnv : controllerToRefereePortEnv
	ChallengeSystem_TrajToPlayerPortSys -- ChallengeEnv_TrajToPlayerPortEnv : trajToPlayerPortEnv
	ChallengeSystem_TrajToRefereePortSys -- ChallengeEnv_TrajToRefereePortEnv : trajToRefereePortEnv
@enduml
